version: "3"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  openapi:
    ports:
      - "8080:8080"
    image: swaggerapi/swagger-ui
    volumes:
      - ${PWD}:/data
    environment:
      SWAGGER_JSON: /data/openapi.yaml