version: "3"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./dbdata:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  openapi:
    ports:
      - "8080:8080"
    image: swaggerapi/swagger-ui
    volumes:
      - .:/data
    environment:
      SWAGGER_JSON: /data/openapi.yaml
  consul:
    image: consul
    restart: always
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600/udp"
    volumes:
      - ./consuldata:/consul/data
    command: "agent -dev -client=0.0.0.0"